services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - chehoch-prod
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - .postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: urodstvo
      POSTGRES_PASSWORD: urodstvo
      POSTGRES_DB: urodstvo
    networks:
      - chehoch-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urodstvo"]
      interval: 2s
      timeout: 5s
      retries: 10

  redis:
    container_name: "redis"
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8800:8001"
    volumes:
      - .redis:/data
    networks:
      - chehoch-prod

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .minio:/data
      - .minio-config:/root/.minio
    environment:
      MINIO_ROOT_USER: urodstvo
      MINIO_ROOT_PASSWORD: urodstvo
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    networks:
      - chehoch-prod

  survey:
    build:
      context: .
      dockerfile: ./apps/survey/Dockerfile
    working_dir: /app/apps/survey
    command: python -m server
    ports:
      - "8001:8001"
    env_file: .env
    networks:
      - chehoch-prod
    depends_on:
      - postgres
      - auth

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "8002:8002"
    env_file: .env
    networks:
      - chehoch-prod
    depends_on:
      - postgres
      - redis

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    working_dir: /app/apps/api
    command: python -m server
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - chehoch-prod
    depends_on:
      - survey
      - auth
      - minio

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    # command: node /app/frontend/dist/server.js
    ports:
      - "3000:3000"
    networks:
      - chehoch-prod

volumes:
  .redis:
  .postgres:
  .minio:
  .minio-config:

networks:
  chehoch-prod:
    driver: bridge
