services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - chehoch-dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - .postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: urodstvo
      POSTGRES_PASSWORD: urodstvo
      POSTGRES_DB: urodstvo
    networks:
      - chehoch-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urodstvo"]
      interval: 2s
      timeout: 5s
      retries: 10

  redis:
    container_name: "redis"
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8800:8001"
    volumes:
      - .redis:/data
    networks:
      - chehoch-dev

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .minio:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS}
      MINIO_SECRET_KEY: ${MINIO_SECRET}
      MINIO_ROOT_USER: urodstvo
      MINIO_ROOT_PASSWORD: urodstvo
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data

volumes:
  .redis:
  .postgres:
  .minio:

networks:
  chehoch-dev:
    driver: bridge
