version: "3.9"

services:
  adminer_auth:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - chehoch-dev

  adminer_survey:
    image: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5433
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - chehoch-dev
    depends_on:
      postgres_survey:
        condition: service_healthy

  postgres_auth:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: urodstvo
      POSTGRES_PASSWORD: urodstvo
      POSTGRES_DB: urodstvo
    networks:
      - chehoch-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urodstvo"]
      interval: 2s
      timeout: 5s
      retries: 10

  postgres_survey:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: urodstvo
      POSTGRES_PASSWORD: urodstvo
      POSTGRES_DB: urodstvo
    networks:
      - chehoch-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urodstvo"]
      interval: 2s
      timeout: 5s
      retries: 10

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8800:8001"
    volumes:
      - redis-data:/data
    networks:
      - chehoch-dev

  survey:
    build: apps/survey
    restart: always
    container_name: "survey-service"
    command: python -m server.py
    env_file:
      - .env
    volumes:
      - apps/survey:/usr/src/app
    ports:
      - 8001:8001
    networks:
      - chehoch-dev
    depends_on:
      postgres_survey:
        condition: service_healthy
      redis:

volumes:
  redis-data:
  postgres-data:
  apps/survey:

networks:
  chehoch-dev:
    driver: bridge
