version: "3.9"

services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - chehoch-dev

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: urodstvo
      POSTGRES_PASSWORD: urodstvo
      POSTGRES_DB: urodstvo
    networks:
      - chehoch-dev

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    networks:
      - chehoch-dev

volumes:
  redis-data:
  postgres-data:

networks:
  chehoch-dev:
    driver: bridge
